version: '2.1'

services:
  react-template:
    image: react-template
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    ## set your startup file here
    command: npm run start